### NEW SAMPLE WITHOUT API KEY -- MUST FAIL
POST http://localhost:3000/api/samples/new HTTP/1.1
content-type: application/json

{
    "temperature": 30,
    "humidity": 0.4,
    "location": {
        "type": "Point",
        "coordinates": [-122.5, 37.7]
    }
}

### NEW SAMPLE WITH API KEY -- MUST SUCCEED
POST http://localhost:3000/api/samples/new HTTP/1.1
content-type: application/json

{
    "temperature": 20,
    "humidity": 0.3,
    "location": {
        "type": "Point",
        "coordinates": [-121.5, 372.7]
    },
    "apiKey": "VGRJ2QH-W0SMGJ4-NG101ZW-K5R0PPZ"
}

### GET REQUEST WITHOUT API KEY -- MUST FAIL
GET http://localhost:3000/api/samples HTTP/1.1

### GET REQUEST WITH API KEY -- MUST SUCCEED
GET http://localhost:3000/api/samples?apiKey=VGRJ2QH-W0SMGJ4-NG101ZW-K5R0PPZ HTTP/1.1
content-type: application/json

### POST FOR NEW USER -- MUST FAIL, SINCE ITS ALREADY CREATED
POST http://localhost:3000/users/new HTTP/1.1
content-type: application/json

{
    "username": "anietog1",
    "password": "secret"
}